apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendaymen
spec:
  selector:
    matchLabels:
      app: backendaymen
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 50%
  #     maxSurge: 50%
  template:
    metadata:
      labels:
        app: backendaymen
    spec:
      containers:
        - name: backendaymen
          image: aymenbentaieb/myappbackend:1.0.0
          ports:
            - containerPort: 3700
          env:
            - name: MONGO_URI
              value: mongodb://mongodbaymen:27017/crud-users-db
            - name: PORT
              value: "3700"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backendaymen 
spec:
  selector:
    app: backendaymen
  ports:
    - protocol: TCP
      port: 3700
      targetPort: 3700