apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <your-backend-image>
          ports:
            - containerPort: 3700
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/crud-users-db
            - name: PORT
              value: "3700"