apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # image: chamseddinedocker/crudappfrontend:latest
          image: crudappcontainerregistry.azurecr.io/frontend:v2
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: backend:3700