apiVersion: v1
kind: Service
metadata:
  name: frontendaymen
spec:
  selector:
    app: frontendaymen
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendaymen
spec:
  selector:
    matchLabels:
      app: frontendaymen
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 50%
  #     maxSurge: 50%
  template:
    metadata:
      labels:
        app: frontendaymen
    spec:
      containers:
        - name: frontendaymen
          image: aymenbentaieb/myappfrontend:1.0.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://backendaymen:3700